apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko-job
  namespace: tyuan
spec:
  completions: 1
  template:
    metadata:
      name: kaniko-job
    spec:
      ttlSecondsAfterFinished: 60
      restartPolicy: Never
      initContainers:
        - name: git-pull-init
          image: alpine/git:latest
          args: ["clone","https://github.com/tyuan/vcas-demo.git","/workspace"]
          volumeMounts:
            - name: workspace-vol
              mountPath: /workspace
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:latest
        args: ["--dockerfile=/workspace/Dockerfile",
               "--context=/workspace",
               "--destination=cdan/vcas-demo:$${GIT_COMMIT_ID}"]
        volumeMounts:
          - name: workspace-vol
            mountPath: /workspace
          - name:  registry-creds
            mountPath: /root/
      volumes:
      - name: registry-creds
        projected:
          sources:
          - secret:
              name: docker-secret-tyuan
              items:
              - key: .dockerconfigjson
                path: .docker/config.json
      - name: workspace-vol
        emptyDir: {}
